### ISSUE TITLE
--threads bug? 

### ISSUE THREAD

**Issue by schultzm** [sanger-pathogens/ariba#155]
It seems that setting `--threads` to anything greater than 1 causes the following error:

```
Signal 15 received in cluster tolC... Stopping!
Process ForkPoolWorker-4:
Signal 15 received in cluster tolC... Stopping!
Process ForkPoolWorker-1:
Signal 15 received in cluster tolC... Stopping!
Process ForkPoolWorker-3:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/site-packages/ariba/cluster.py", line 154, in _receive_signal
    with open(self.fail_file, 'w') as f:
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/site-packages/ariba/cluster.py", line 154, in _receive_signal
    with open(self.fail_file, 'w') as f:
Signal 15 received in cluster tolC... Stopping!
FileNotFoundError: [Errno 2] No such file or directory: '/home/schultzm/scripts/schultzm/development/results/2014-00065/ariba_CARD/.fails/tolC'
FileNotFoundError: [Errno 2] No such file or directory: '/home/schultzm/scripts/schultzm/development/results/2014-00065/ariba_CARD/.fails/tolC'
```

**Comment by schultzm** [comment]
This command runs to completion:
`ariba run --threads 1 --force CARD /mnt/seq/MDU/READS/2014-00065/2014-00065_R1.fastq.gz /mnt/seq/MDU/READS/2014-00065/2014-00065_R2.fastq.gz ../results/2014-00065/ariba_CARD`

This command generated the above error:

`ariba run --threads 2 --force CARD /mnt/seq/MDU/READS/2014-00065/2014-00065_R1.fastq.gz /mnt/seq/MDU/READS/2014-00065/2014-00065_R2.fastq.gz ../results/2014-00065/ariba_CARD`

**Comment by martinghunt** [comment]
The threads option is experimental and should be considered unstable.

I have seen this error happen when there is not enough ram. But other than that it's hard to debug the threads option. ARIBA is usually quite fast, so sorry but this is honestly not high on my priority list.
