### ISSUE TITLE
error generating cluster

### ISSUE THREAD

**Issue by schultzm** [sanger-pathogens/ariba#157]
Hi, 

There appears to be an error in the code with a list index out of range.  

```
ariba run --verbose --force CARD /mnt/seq/MDU/READS/ariba_bug_reads/ariba_bug_reads_R1.fastq.gz /mnt/seq/MDU/READS/ariba_bug_reads/ariba_bug_reads_R2.fastq.gz /home/schultzm/scripts/schultzm/development/results/ariba_bug_reads/ariba_CARD
Found reads file: /mnt/seq/MDU/READS/ariba_bug_reads/ariba_bug_reads_R1.fastq.gz
Found reads file: /mnt/seq/MDU/READS/ariba_bug_reads/ariba_bug_reads_R2.fastq.gz
ARIBA version: 2.6.1

External dependencies:
bowtie2	2.2.9	/home/linuxbrew/.linuxbrew/bin/bowtie2
cdhit	4.6	/home/linuxbrew/.linuxbrew/bin/cd-hit-est
nucmer	3.1	/home/linuxbrew/.linuxbrew/bin/nucmer

External dependencies OK: True

Python version:
3.5.2 (default, Nov  7 2016, 09:25:32) 
[GCC 5.3.0]

Python packages:
ariba	2.6.1	/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/site-packages/ariba/__init__.py
dendropy	4.2.0	/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/site-packages/dendropy/__init__.py
pyfastaq	3.14.0	/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/site-packages/pyfastaq/__init__.py
pymummer	0.10.1	/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/site-packages/pymummer/__init__.py
pysam	0.9.1.4	/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/site-packages/pysam/__init__.py

Python packages OK: True

Everything looks OK: True
Temporary directory: /tmp/schultzm/ariba.tmp.8gwpiegs
______________________ Mapping reads to clustered genes _______________________
Finished mapping

_____________________________ Generating clusters _____________________________
syscall: sort -k1,1 -k 2,2n /home/schultzm/scripts/schultzm/development/results/ariba_bug_reads/ariba_CARD/minimap.reads > /home/schultzm/scripts/schultzm/development/results/ariba_bug_reads/ariba_CARD/read_store
Compressing file /home/schultzm/scripts/schultzm/development/results/ariba_bug_reads/ariba_CARD/read_store
Found 12066 proper read pairs from minimap
Total clusters to perform local assemblies: 69

Insert size information from reads mapped to reference genes:
Insert size:	285.0
Insert sspace sd:	0.79
Max insert:	561.5500000000001

___________________________ Assembling each cluster ___________________________
Will run 1 cluster(s) in parallel
Constructing cluster AAC_3__Ib (1 of 69)
Constructing cluster AAC_3__Ib_AAC_6___Ib__ (2 of 69)
Constructing cluster AAC_6___30_AAC_6___Ib__fusion_protein (3 of 69)
Constructing cluster AAC_6___31 (4 of 69)
Constructing cluster AAC_6___Ib+ (5 of 69)
Constructing cluster ANT_2____Ia (6 of 69)
Constructing cluster APH_3___Ia (7 of 69)
Constructing cluster CRP (8 of 69)
Constructing cluster Chlamydophila_psittaci_16S (9 of 69)
Constructing cluster Enterobacter_aerogenes_omp36 (10 of 69)
Constructing cluster Escherichia_coli_EF_Tu (11 of 69)
Constructing cluster Escherichia_coli_mutant (12 of 69)
Constructing cluster Escherichia_coli_mutant_1 (13 of 69)
Constructing cluster FosA5 (14 of 69)
Constructing cluster H_NS (15 of 69)
Constructing cluster Helicobacter_pylori_16S (16 of 69)
Constructing cluster KPC_- (17 of 69)
Constructing cluster Klebsiella_OmpK35_conferring (18 of 69)
Constructing cluster Klebsiella_OmpK36_conferring (19 of 69)
Constructing cluster Klebsiella_mutant_PhoP (20 of 69)
Constructing cluster LEN_1+ (21 of 69)
Constructing cluster Mrx (22 of 69)
Constructing cluster Mycobacterium_abscessus_16S+ (23 of 69)
Constructing cluster Neisseria_- (24 of 69)
Constructing cluster OKP_- (25 of 69)
Constructing cluster OXA_9 (26 of 69)
Constructing cluster Pasteurella_multocida_16S (27 of 69)
Constructing cluster Propionibacterium_acnes_16S (28 of 69)
Constructing cluster SHV_- (29 of 69)
Constructing cluster TEM_- (30 of 69)
Constructing cluster aadA- (31 of 69)
Constructing cluster aadA-_1 (32 of 69)
Constructing cluster aadA9 (33 of 69)
Constructing cluster acrA (34 of 69)
Constructing cluster acrA_1 (35 of 69)
Constructing cluster acrB (36 of 69)
Constructing cluster acrD (37 of 69)
Constructing cluster acrR (38 of 69)
Constructing cluster acrR_1 (39 of 69)
Constructing cluster alaS (40 of 69)
Constructing cluster arnA (41 of 69)
Constructing cluster cat+ (42 of 69)
Not constructing cluster dfrA- because it only has 2 reads (43 of 69)
Constructing cluster dfrA12 (44 of 69)
Constructing cluster emrB (45 of 69)
Constructing cluster fyuA (46 of 69)
Constructing cluster gyrA_6 (47 of 69)
Constructing cluster gyrA_7 (48 of 69)
Constructing cluster gyrB_1 (49 of 69)
Constructing cluster mdtA (50 of 69)
Not constructing cluster mdtB because it only has 2 reads (51 of 69)
Constructing cluster mdtC (52 of 69)
Constructing cluster mdtD (53 of 69)
Constructing cluster mphA (54 of 69)
Constructing cluster murA_12 (55 of 69)
Constructing cluster ompF (56 of 69)
Constructing cluster oqxA (57 of 69)
Constructing cluster oqxB (58 of 69)
Constructing cluster parC_2 (59 of 69)
Constructing cluster parC_3 (60 of 69)
Not constructing cluster parE_2 because it only has 2 reads (61 of 69)
Constructing cluster patA (62 of 69)
Constructing cluster ramR_1 (63 of 69)
Constructing cluster rpoB (64 of 69)
Constructing cluster rrsB+ (65 of 69)
Constructing cluster smeE (66 of 69)
Constructing cluster sul1 (67 of 69)
Constructing cluster tolC (68 of 69)
Constructing cluster vgaC (69 of 69)
Start running cluster AAC_3__Ib in directory /tmp/schultzm/ariba.tmp.8gwpiegs/AAC_3__Ib
Finished running cluster AAC_3__Ib in directory /tmp/schultzm/ariba.tmp.8gwpiegs/AAC_3__Ib
Deleting cluster dir /tmp/schultzm/ariba.tmp.8gwpiegs/AAC_3__Ib
Start running cluster AAC_3__Ib_AAC_6___Ib__ in directory /tmp/schultzm/ariba.tmp.8gwpiegs/AAC_3__Ib_AAC_6___Ib__
Finished running cluster AAC_3__Ib_AAC_6___Ib__ in directory /tmp/schultzm/ariba.tmp.8gwpiegs/AAC_3__Ib_AAC_6___Ib__
Deleting cluster dir /tmp/schultzm/ariba.tmp.8gwpiegs/AAC_3__Ib_AAC_6___Ib__
Start running cluster AAC_6___30_AAC_6___Ib__fusion_protein in directory /tmp/schultzm/ariba.tmp.8gwpiegs/AAC_6___30_AAC_6___Ib__fusion_protein
Finished running cluster AAC_6___30_AAC_6___Ib__fusion_protein in directory /tmp/schultzm/ariba.tmp.8gwpiegs/AAC_6___30_AAC_6___Ib__fusion_protein
Deleting cluster dir /tmp/schultzm/ariba.tmp.8gwpiegs/AAC_6___30_AAC_6___Ib__fusion_protein
Start running cluster AAC_6___31 in directory /tmp/schultzm/ariba.tmp.8gwpiegs/AAC_6___31
Finished running cluster AAC_6___31 in directory /tmp/schultzm/ariba.tmp.8gwpiegs/AAC_6___31
Deleting cluster dir /tmp/schultzm/ariba.tmp.8gwpiegs/AAC_6___31
Start running cluster AAC_6___Ib+ in directory /tmp/schultzm/ariba.tmp.8gwpiegs/AAC_6___Ib+
Error making report for cluster  AAC_6___Ib+ ... traceback:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/site-packages/ariba/cluster.py", line 425, in _run
    self.report_lines = report.report_lines(self)
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/site-packages/ariba/report.py", line 375, in report_lines
    lines.extend(_report_lines_for_one_contig(cluster, contig_name, ref_cov_per_contig, contig_pymummer_variants))
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/site-packages/ariba/report.py", line 332, in _report_lines_for_one_contig
    ref_nt = cluster.ref_sequence[ref_coord]
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/site-packages/pyfastaq/sequences.py", line 424, in __getitem__
    return self.seq[index]
IndexError: string index out of range
Failed cluster: AAC_6___Ib+
Finished running cluster AAC_6___Ib+ in directory /tmp/schultzm/ariba.tmp.8gwpiegs/AAC_6___Ib+
Deleting cluster dir /tmp/schultzm/ariba.tmp.8gwpiegs/AAC_6___Ib+
Other clusters failed. Will not start cluster ANT_2____Ia
Other clusters failed. Will not start cluster APH_3___Ia
Other clusters failed. Will not start cluster CRP
Other clusters failed. Will not start cluster Chlamydophila_psittaci_16S
Other clusters failed. Will not start cluster Enterobacter_aerogenes_omp36
Other clusters failed. Will not start cluster Escherichia_coli_EF_Tu
Other clusters failed. Will not start cluster Escherichia_coli_mutant
Other clusters failed. Will not start cluster Escherichia_coli_mutant_1
Other clusters failed. Will not start cluster FosA5
Other clusters failed. Will not start cluster H_NS
Other clusters failed. Will not start cluster Helicobacter_pylori_16S
Other clusters failed. Will not start cluster KPC_-
Other clusters failed. Will not start cluster Klebsiella_OmpK35_conferring
Other clusters failed. Will not start cluster Klebsiella_OmpK36_conferring
Other clusters failed. Will not start cluster Klebsiella_mutant_PhoP
Other clusters failed. Will not start cluster LEN_1+
Other clusters failed. Will not start cluster Mrx
Other clusters failed. Will not start cluster Mycobacterium_abscessus_16S+
Other clusters failed. Will not start cluster Neisseria_-
Other clusters failed. Will not start cluster OKP_-
Other clusters failed. Will not start cluster OXA_9
Other clusters failed. Will not start cluster Pasteurella_multocida_16S
Other clusters failed. Will not start cluster Propionibacterium_acnes_16S
Other clusters failed. Will not start cluster SHV_-
Other clusters failed. Will not start cluster TEM_-
Other clusters failed. Will not start cluster aadA-
Other clusters failed. Will not start cluster aadA-_1
Other clusters failed. Will not start cluster aadA9
Other clusters failed. Will not start cluster acrA
Other clusters failed. Will not start cluster acrA_1
Other clusters failed. Will not start cluster acrB
Other clusters failed. Will not start cluster acrD
Other clusters failed. Will not start cluster acrR
Other clusters failed. Will not start cluster acrR_1
Other clusters failed. Will not start cluster alaS
Other clusters failed. Will not start cluster arnA
Other clusters failed. Will not start cluster cat+
Other clusters failed. Will not start cluster dfrA12
Other clusters failed. Will not start cluster emrB
Other clusters failed. Will not start cluster fyuA
Other clusters failed. Will not start cluster gyrA_6
Other clusters failed. Will not start cluster gyrA_7
Other clusters failed. Will not start cluster gyrB_1
Other clusters failed. Will not start cluster mdtA
Other clusters failed. Will not start cluster mdtC
Other clusters failed. Will not start cluster mdtD
Other clusters failed. Will not start cluster mphA
Other clusters failed. Will not start cluster murA_12
Other clusters failed. Will not start cluster ompF
Other clusters failed. Will not start cluster oqxA
Other clusters failed. Will not start cluster oqxB
Other clusters failed. Will not start cluster parC_2
Other clusters failed. Will not start cluster parC_3
Other clusters failed. Will not start cluster patA
Other clusters failed. Will not start cluster ramR_1
Other clusters failed. Will not start cluster rpoB
Other clusters failed. Will not start cluster rrsB+
Other clusters failed. Will not start cluster smeE
Other clusters failed. Will not start cluster sul1
Other clusters failed. Will not start cluster tolC
Other clusters failed. Will not start cluster vgaC
Finished assembling clusters

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/site-packages/ariba/clusters.py", line 546, in run
    self._run()
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/site-packages/ariba/clusters.py", line 579, in _run
    raise Error('At least one cluster failed! Stopping...')
ariba.clusters.Error: At least one cluster failed! Stopping...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/ariba", line 231, in <module>
    args.func(args)
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/site-packages/ariba/tasks/run.py", line 63, in run
    c.run()
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.5/site-packages/ariba/clusters.py", line 549, in run
    raise Error('Something went wrong during ariba run. Cannot continue. Error was:\n' + str(err))
ariba.clusters.Error: Something went wrong during ariba run. Cannot continue. Error was:
At least one cluster failed! Stopping...
```

**Comment by martinghunt** [comment]
Thanks, that's definitely not right! Could you share the reads with me so I can debug it? What version of card did you use?

**Comment by schultzm** [comment]
Great.  Glad to be of help.  The version of CARD was downloaded using `ariba getref card CARD_database` and `ariba prepareref -f CARD_database.fa -m CARD_database.tsv CARD` with the stamp `2.3M Jan 23 15:04 CARD_database.fa`

**Comment by schultzm** [comment]
```
If you use this downloaded data, please cite:
"The Comprehensive Antibiotic Resistance Database", McArthur et al 2013, PMID: 23650175
and in your methods say that version 1.1.3 of the database was used
```

**Comment by martinghunt** [comment]
Could I get access to the reads somehow please?

**Comment by schultzm** [comment]
please download the reads from (here)[https://bioinformatics.mdu.unimelb.edu.au/~schultzm/]

**Comment by martinghunt** [comment]
Thanks, I've got the reads. Looking into it now...

**Comment by martinghunt** [comment]
Fixed. I did a new ariba release 2.7.2. But the fix is really in pyummer 0.10.2, so make sure you update that as well.

**Comment by tseemann** [comment]
Thanks @martinghunt !

**Comment by lec49** [comment]
Hi, 
I am also having the same issue (getting a simillar error message) when running ariba
How do I ensure I have the up to date packages?

The final part of the error is .....

Other clusters failed. Will not start cluster ERR525828_99998
Other clusters failed. Will not start cluster ERR525828_99999
Stopping! Signal received: 13
Stopping! Signal received: 13
Signal 15 received in cluster ERR525828_99999... Stopping!
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/ariba/clusters.py", line 602, in run
    self._run()
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/ariba/clusters.py", line 636, in _run
    raise Error('At least one cluster failed! Stopping...')
ariba.clusters.Error: At least one cluster failed! Stopping...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/ariba", line 298, in <module>
    args.func(args)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/ariba/tasks/run.py", line 65, in run
    c.run()
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/ariba/clusters.py", line 605, in run
    raise Error('Something went wrong during ariba run. Cannot continue. Error was:\n' + str(err))
ariba.clusters.Error: Something went wrong during ariba run. Cannot continue. Error was:
At least one cluster failed! Stopping...

**Comment by rstabler** [comment]
Hi

New to ariba

I also got "Stopping! Signal received: 13"

Switching assembler did not help. 

=== Stack Trace ===
/usr/lib/spades/bin/spades(_ZN14coverage_model17KMerCoverageModel3FitEv+0x2a9) [0x56136dfcd6e9]
/usr/lib/spades/bin/spades(_ZN14debruijn_graph17GenomicInfoFiller3runERNS_10graph_packINS_13DeBruijnGraphEEEPKc+0x1d4) [0x56136df6cc94]
/usr/lib/spades/bin/spades(_ZN6spades12StageManager3runERN14debruijn_graph10graph_packINS1_13DeBruijnGraphEEEPKc+0xd8) [0x56136df439a8]
/usr/lib/spades/bin/spades(_ZN6spades15assemble_genomeEv+0x9a4) [0x56136de1a734]
/usr/lib/spades/bin/spades(main+0x386) [0x56136de13f36]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fa6d3ecdb97]
/usr/lib/spades/bin/spades(_start+0x2a) [0x56136de1928a]
Verification of expression 'cov_.size() > 10' failed in function 'void coverage_model::KMerCoverageModel::Fit()'. In file '/build/spades-9nQbPn/spades-3.11.1+dfsg/src/common/modules/coverage_model/kmer_coverage_model.cpp' on line 187. Message 'Invalid kmer coverage histogram, make sure that the coverage is indeed uniform'.
Verification of expression 'cov_.size() > 10' failed in function 'void coverage_model::KMerCoverageModel::Fit()'. In file '/build/spades-9nQbPn/spades-3.11.1+dfsg/src/common/modules/coverage_model/kmer_coverage_model.cpp' on line 187. Message 'Invalid kmer coverage histogram, make sure that the coverage is indeed uniform'.
spades: /build/spades-9nQbPn/spades-3.11.1+dfsg/src/common/modules/coverage_model/kmer_coverage_model.cpp:187: void coverage_model::KMerCoverageModel::Fit(): Assertion `cov_.size() > 10' failed.


== Error ==  system call for: "['/usr/lib/spades/bin/spades', '/home/richard/work/project_doyle/ariba/AMRIL_1_spades/ariba.tmp.hkigx28u/parE_1/Assembly/Assemble/K33/configs/config.info', '/home/richard/work/project_doyle/ariba/AMRIL_1_spades/ariba.tmp.hkigx28u/parE_1/Assembly/Assemble/K33/configs/careful_mode.info']" finished abnormally, err code: -6

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

parE_1 reported completion
parC_3 reported completion
porin_OmpC reported completion
ramR_1 detected 1 threads available to it
smeE reported completion
gyrA_8 reported completion
gyrB_1 reported completion
ramR_1 reported completion
rpoB reported completion
rrsB+ detected 8 threads available to it
rrsB+ reported completion
Stopping! Signal received: 13

**Comment by rstabler** [comment]
ARIBA version: 2.11.1

External dependencies:
bowtie2	2.3.4.1	/usr/bin/bowtie2
cdhit	4.7	/usr/bin/cd-hit-est
nucmer	3.1	/usr/bin/nucmer
spades	3.11.1	/usr/bin/spades.py

External dependencies OK: True

Python version:
3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0]

Python packages:
ariba	2.11.1	/usr/lib/python3/dist-packages/ariba/__init__.py
bs4	4.6.0	/usr/lib/python3/dist-packages/bs4/__init__.py
dendropy	4.3.0	/usr/lib/python3/dist-packages/dendropy/__init__.py
pyfastaq	3.17.0	/usr/lib/python3/dist-packages/pyfastaq/__init__.py
pymummer	0.10.3	/usr/lib/python3/dist-packages/pymummer/__init__.py
pysam	0.14	/usr/lib/python3/dist-packages/pysam/__init__.py

Python packages OK: True

Everything looks OK: True
