### ISSUE TITLE
Failing to build wheel

### ISSUE THREAD

**Issue by karinlag** [sanger-pathogens/ariba#168]
I am installing 2.9 on a cluster now (redhat).

I fail building wheel, and I get this as the error just before Failing building wheel for ariba:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-3radi493/ariba/setup.py", line 81, in <module>
      'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
    File "/cluster/software/VERSIONS/python3-3.5.0/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/cluster/software/VERSIONS/python3-3.5.0/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/cluster/software/VERSIONS/python3-3.5.0/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/work/projects/nn9305k/bin/virtenv/ariba/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/work/projects/nn9305k/bin/virtenv/ariba/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/work/projects/nn9305k/bin/virtenv/ariba/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError
  
What is this assertion that is failing?

**Comment by martinghunt** [comment]
Sorry, don't know without looking into it more. What version of redhat are you running? I can see if I can reproduce the error.

Alternatively, you could try downlaoding the tarball release, unpacking and doing `python3 setup.py install`.

**Comment by karinlag** [comment]
I got it to install!

I just had to completely eradicate my PYTHONPATH, and then do pip with the no-cache option. Of course, now I have a problem with GLIBCXX something or other due to the cython code in it, but I've taken that up with the cluster IT people :)
