### ISSUE TITLE
TypeError 

### ISSUE THREAD

**Issue by karinlag** [sanger-pathogens/ariba#197]
I get the following when simply trying to figure out the ariba version:

(ariba) [karinlag@abel ~]$ ariba version
Traceback (most recent call last):
  File "/work/projects/nn9305k/src/anaconda3/bin/ariba", line 292, in <module>
    args.func(args)
  File "/work/projects/nn9305k/src/anaconda3/lib/python3.6/site-packages/ariba/tasks/version.py", line 5, in run
    extern_progs, report_lines = versions.get_all_versions(raise_error=False)
  File "/work/projects/nn9305k/src/anaconda3/lib/python3.6/site-packages/ariba/versions.py", line 21, in get_all_versions
    extern_progs = external_progs.ExternalProgs(fail_on_error=False)
  File "/work/projects/nn9305k/src/anaconda3/lib/python3.6/site-packages/ariba/external_progs.py", line 65, in __init__
    if prog in min_versions and LooseVersion(version) < LooseVersion(min_versions[prog]):
  File "/work/projects/nn9305k/src/anaconda3/lib/python3.6/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/work/projects/nn9305k/src/anaconda3/lib/python3.6/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
(ariba) [karinlag@abel ~]$ 

Am I messing up something, or is this something with the code?

Pip installed ariba this morning, btw.

**Comment by andrewjpage** [comment]
It looks like the version string coming back from one of the programs is causing it to fail. Could you send the output of running these commands?

```
bowtie2 --version
cdhit
nucmer --version
```

**Comment by karinlag** [comment]
I figured out that this was caused by issues with the cluster I was running it on - apparently mummer messes up the bowtie2 program. Thanks for helping me ID the problem!

**Comment by andrewjpage** [comment]
Glad you got it sorted.
