### ISSUE TITLE
unable to download mlst schemes

### ISSUE THREAD

**Issue by samlipworth** [sanger-pathogens/ariba#264]
Traceback (most recent call last):
  File "/usr/local/bin/ariba", line 4, in <module>
    __import__('pkg_resources').run_script('ariba==2.13.4', 'ariba')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/ariba-2.13.4-py3.6-linux-x86_64.egg/EGG-INFO/scripts/ariba", line 310, in <module>
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/ariba-2.13.4-py3.6-linux-x86_64.egg/ariba/tasks/pubmlstget.py", line 11, in run
    preparer.run()
  File "/usr/local/lib/python3.6/dist-packages/ariba-2.13.4-py3.6-linux-x86_64.egg/ariba/pubmlst_ref_preparer.py", line 75, in run
    pubmlst = pubmlst_getter.PubmlstGetter(debug=self.debug, verbose=self.verbose)
  File "/usr/local/lib/python3.6/dist-packages/ariba-2.13.4-py3.6-linux-x86_64.egg/ariba/pubmlst_getter.py", line 19, in __init__
    self.xml_tree = self._get_xml_file_tree()
  File "/usr/local/lib/python3.6/dist-packages/ariba-2.13.4-py3.6-linux-x86_64.egg/ariba/pubmlst_getter.py", line 28, in _get_xml_file_tree
    self._download_file(xml_url, xml_file)
  File "/usr/local/lib/python3.6/dist-packages/ariba-2.13.4-py3.6-linux-x86_64.egg/ariba/pubmlst_getter.py", line 50, in _download_file
    raise Error('Error downloading: ' + url)
ariba.pubmlst_getter.Error: Error downloading: http://pubmlst.org/data/dbases.xml

**Comment by samlipworth** [comment]
I have tried this in several ways - perhaps is is related to the file on pubmlst which actually appears to be empty.  I have been able to execute this function successfuly in the past..

**Comment by samlipworth** [comment]
This was due to an error with the pubmlst site - the dbases.xml file was empty because of a server error in Oxford's zoology dept - this is now fixed and so I am closing this.
