### ISSUE TITLE
PubMLST URL change breaks pubmlstget

### ISSUE THREAD

**Issue by rpetit3** [sanger-pathogens/ariba#304]
`ariba pubmlstget "Staphylococcus aureus" datasets/species-specific/staphylococcus-aureus/mlst/default/ariba'`

```
WARNING: I tried to get the version of spades with: "/home/rpetit/miniconda3/envs/bactopia/bin/spades.py --version" and the output didn't match this regular expression: "SPAdes\s+v([0-9\.]+)"
Traceback (most recent call last):
  File "/home/rpetit/miniconda3/envs/bactopia/bin/ariba", line 312, in <module>
    args.func(args)
  File "/home/rpetit/miniconda3/envs/bactopia/lib/python3.6/site-packages/ariba/tasks/pubmlstget.py", line 11, in run
    preparer.run()
  File "/home/rpetit/miniconda3/envs/bactopia/lib/python3.6/site-packages/ariba/pubmlst_ref_preparer.py", line 85, in run
    self._load_fasta_files_and_write_clusters_file(self.mlst_download_dir)
  File "/home/rpetit/miniconda3/envs/bactopia/lib/python3.6/site-packages/ariba/pubmlst_ref_preparer.py", line 49, in _load_fasta_files_and_write_clusters_file
    raise Error('Cannot find file "' + infile + '" for gene ' + gene_name)
```

verbose output
```
Downloading "http://pubmlst.org/data/dbases.xml" and saving as "/home/rpetit/test-grounds/tmp.get_pubmlst_xmlxwc5g9c5/out.xml" ...
Downloading "https://rest.pubmlst.org/db/pubmlst_saureus_seqdef/schemes/1/profiles_csv" and saving as "datasets/species-specific/staphylococcus-aureus/mlst/default/ariba/pubmlst_download/profile.txt" ...
Downloading "https://rest.pubmlst.org/db/pubmlst_saureus_seqdef/loci/arcC/alleles_fasta" and saving as "datasets/species-specific/staphylococcus-aureus/mlst/default/ariba/pubmlst_download/alleles_fasta.tmp" ...
Downloading "https://rest.pubmlst.org/db/pubmlst_saureus_seqdef/loci/aroE/alleles_fasta" and saving as "datasets/species-specific/staphylococcus-aureus/mlst/default/ariba/pubmlst_download/alleles_fasta.tmp" ...
Downloading "https://rest.pubmlst.org/db/pubmlst_saureus_seqdef/loci/glpF/alleles_fasta" and saving as "datasets/species-specific/staphylococcus-aureus/mlst/default/ariba/pubmlst_download/alleles_fasta.tmp" ...
Downloading "https://rest.pubmlst.org/db/pubmlst_saureus_seqdef/loci/gmk/alleles_fasta" and saving as "datasets/species-specific/staphylococcus-aureus/mlst/default/ariba/pubmlst_download/alleles_fasta.tmp" ...
Downloading "https://rest.pubmlst.org/db/pubmlst_saureus_seqdef/loci/pta/alleles_fasta" and saving as "datasets/species-specific/staphylococcus-aureus/mlst/default/ariba/pubmlst_download/alleles_fasta.tmp" ...
Downloading "https://rest.pubmlst.org/db/pubmlst_saureus_seqdef/loci/tpi/alleles_fasta" and saving as "datasets/species-specific/staphylococcus-aureus/mlst/default/ariba/pubmlst_download/alleles_fasta.tmp" ...
Downloading "https://rest.pubmlst.org/db/pubmlst_saureus_seqdef/loci/yqiL/alleles_fasta" and saving as "datasets/species-specific/staphylococcus-aureus/mlst/default/ariba/pubmlst_download/alleles_fasta.tmp"
```

Looks like the change in API endpoint is causing all the files are being named *alleles_fasta* (alleles_fasta) instead of the expected *loci_name.tfa* (arcC.tfa).

Getting the same error for multiple species

**Comment by rpetit3** [comment]
This is fixed on the Bioconda side. You will need to update Ariba in your Conda environment.

```
conda update -c conda-forge -c bioconda ariba
```

You should see something like:

```
The following packages will be UPDATED:

  ariba                               2.14.5-py36hf0b53f7_1 --> 2.14.5-py36hf0b53f7_2
```

After update:

```
ariba pubmlstget "Staphylococcus aureus" test-pubs
WARNING: I tried to get the version of spades with: "/local/home/rpetit/miniconda3/envs/bactopia/bin/spades.py --version" and the output didn't match this regular expression: "SPAdes\s+v([0-9\.]+)"
WARNING: Median sequence length is 456 but arcC.548 has length 522 which is too long or short. Removing.
WARNING: Median sequence length is 456 but arcC.567 has length 516 which is too long or short. Removing.
ariba db directory prepared. You can use it like this:
ariba run test-pubs/ref_db reads_1.fq reads_2.fq output_directory
```

**Comment by puethe** [comment]
Solved with https://github.com/sanger-pathogens/ariba/pull/305

**Comment by lskatz** [comment]
Hello from the future! What is the fix? I have installed it on conda but get this error

```shell
(ariba) lkatz@localhost:~$ ariba pubmlstspecies
/home/lkatz/miniconda3/envs/ariba/lib/python3.9/site-packages/ariba/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution
/home/lkatz/miniconda3/envs/ariba/lib/python3.9/site-packages/numpy/_core/getlimits.py:545: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)
Traceback (most recent call last):
  File "/home/lkatz/miniconda3/envs/ariba/bin/ariba", line 312, in <module>
    args.func(args)
  File "/home/lkatz/miniconda3/envs/ariba/lib/python3.9/site-packages/ariba/tasks/pubmlstspecies.py", line 6, in run
    getter = pubmlst_getter.PubmlstGetter()
  File "/home/lkatz/miniconda3/envs/ariba/lib/python3.9/site-packages/ariba/pubmlst_getter.py", line 19, in __init__
    self.xml_tree = self._get_xml_file_tree()
  File "/home/lkatz/miniconda3/envs/ariba/lib/python3.9/site-packages/ariba/pubmlst_getter.py", line 28, in _get_xml_file_tree
    self._download_file(xml_url, xml_file)
  File "/home/lkatz/miniconda3/envs/ariba/lib/python3.9/site-packages/ariba/pubmlst_getter.py", line 50, in _download_file
    raise Error('Error downloading: ' + url)
ariba.pubmlst_getter.Error: Error downloading: http://pubmlst.org/data/dbases.xml
```

```text
(ariba) lkatz@localhost:~$ conda list
# packages in environment at /home/lkatz/miniconda3/envs/ariba:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
ariba                     2.14.6           py39h67e14b5_3    bioconda
bcftools                  1.21                 h8b25389_0    bioconda
beautifulsoup4            4.13.4             pyha770c72_0    conda-forge
biopython                 1.85             py39h8cd3c5a_1    conda-forge
bowtie2                   2.2.5            py39h7cff6ad_8    bioconda
brotli                    1.1.0                hb03c661_4    conda-forge
brotli-bin                1.1.0                hb03c661_4    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.5               hb9d3cd8_0    conda-forge
ca-certificates           2025.8.3             hbd8a1cb_0    conda-forge
cd-hit                    4.8.1               h43eeafb_11    bioconda
certifi                   2025.8.3           pyhd8ed1ab_0    conda-forge
contourpy                 1.3.0            py39h74842e3_2    conda-forge
cycler                    0.12.1             pyhd8ed1ab_1    conda-forge
dendropy                  5.0.8              pyhdfd78af_1    bioconda
fonttools                 4.59.1           py39heb7d2ae_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
htslib                    1.21                 h5efdd21_0    bioconda
importlib-resources       6.5.2              pyhd8ed1ab_0    conda-forge
importlib_resources       6.5.2              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.3                hb9d3cd8_0    conda-forge
kiwisolver                1.4.7            py39h74842e3_0    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.44                 h1423503_1    conda-forge
lerc                      4.0.0                h0aef613_1    conda-forge
libasprintf               0.25.1               h3f43e3d_1    conda-forge
libblas                   3.9.0           34_h59b9bed_openblas    conda-forge
libbrotlicommon           1.1.0                hb03c661_4    conda-forge
libbrotlidec              1.1.0                hb03c661_4    conda-forge
libbrotlienc              1.1.0                hb03c661_4    conda-forge
libcblas                  3.9.0           34_he106b2a_openblas    conda-forge
libcurl                   8.8.0                hca28451_1    conda-forge
libdeflate                1.20                 hd590300_0    conda-forge
libedit                   3.1.20250104    pl5321h7949ede_0    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.6                h2dba641_1    conda-forge
libgcc                    15.1.0               h767d61c_4    conda-forge
libgcc-ng                 15.1.0               h69a702a_4    conda-forge
libgettextpo              0.25.1               h3f43e3d_1    conda-forge
libgfortran               15.1.0               h69a702a_4    conda-forge
libgfortran5              15.1.0               hcea5267_4    conda-forge
libgomp                   15.1.0               h767d61c_4    conda-forge
libiconv                  1.18                 h3b78370_2    conda-forge
libidn2                   2.3.8                ha4ef2c3_0    conda-forge
libjpeg-turbo             3.1.0                hb9d3cd8_0    conda-forge
liblapack                 3.9.0           34_h7ac8fdf_openblas    conda-forge
liblzma                   5.8.1                hb9d3cd8_2    conda-forge
liblzma-devel             5.8.1                hb9d3cd8_2    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hb9d3cd8_1    conda-forge
libopenblas               0.3.30          pthreads_h94d23a6_2    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx                 15.1.0               h8f9b012_4    conda-forge
libstdcxx-ng              15.1.0               h4852527_4    conda-forge
libtiff                   4.6.0                h1dd3fc0_3    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.6.0                hd42ef1d_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
matplotlib-base           3.9.4            py39h16632d1_0    conda-forge
mummer                    3.23            pl5321h503566f_21    bioconda
munkres                   1.1.4              pyhd8ed1ab_1    conda-forge
ncurses                   6.5                  h2d0b736_3    conda-forge
numpy                     2.0.2            py39h9cb892a_1    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.5.2                h26f9b46_0    conda-forge
packaging                 25.0               pyh29332c3_1    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
pillow                    10.3.0           py39h90c7501_0    conda-forge
pip                       25.2               pyh8b19718_0    conda-forge
pthread-stubs             0.4               hb9d3cd8_1002    conda-forge
pyfastaq                  3.18.0             pyhdfd78af_0    bioconda
pymummer                  0.10.3                     py_2    bioconda
pyparsing                 3.2.3              pyhe01879c_2    conda-forge
pysam                     0.22.1           py39h61809e1_2    bioconda
python                    3.9.19          h0755675_0_cpython    conda-forge
python-dateutil           2.9.0.post0        pyhe01879c_2    conda-forge
python_abi                3.9                      8_cp39    conda-forge
qhull                     2020.2               h434a139_5    conda-forge
readline                  8.2                  h8c095d6_2    conda-forge
samtools                  1.21                 h50ea8bc_0    bioconda
setuptools                80.9.0             pyhff2d567_0    conda-forge
six                       1.17.0             pyhe01879c_1    conda-forge
soupsieve                 2.7                pyhd8ed1ab_0    conda-forge
spades                    4.0.0                h6dccd9a_3    bioconda
tk                        8.6.13          noxft_h4845f30_101    conda-forge
typing-extensions         4.14.1               h4440ef1_0    conda-forge
typing_extensions         4.14.1             pyhe01879c_0    conda-forge
tzdata                    2025b                h78e105d_0    conda-forge
unicodedata2              16.0.0           py39h8cd3c5a_0    conda-forge
wget                      1.21.4               hda4d442_0    conda-forge
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
xorg-libxau               1.0.12               hb9d3cd8_0    conda-forge
xorg-libxdmcp             1.1.5                hb9d3cd8_0    conda-forge
xz                        5.8.1                hbcc6ac9_2    conda-forge
xz-gpl-tools              5.8.1                hbcc6ac9_2    conda-forge
xz-tools                  5.8.1                hb9d3cd8_2    conda-forge
zipp                      3.23.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```
