### ISSUE TITLE
Unable to download Escherichia coli#1 and Escherichia coli#2

### ISSUE THREAD

**Issue by RotimiDada** [sanger-pathogens/ariba#308]
Traceback (most recent call last):
  File "/usr/local/bin/ariba", line 4, in <module>
    __import__('pkg_resources').run_script('ariba==2.14.4', 'ariba')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/ariba-2.14.4-py3.6-linux-x86_64.egg/EGG-INFO/scripts/ariba", line 312, in <module>
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/ariba-2.14.4-py3.6-linux-x86_64.egg/ariba/tasks/pubmlstget.py", line 11, in run
    preparer.run()
  File "/usr/local/lib/python3.6/dist-packages/ariba-2.14.4-py3.6-linux-x86_64.egg/ariba/pubmlst_ref_preparer.py", line 85, in run
    self._load_fasta_files_and_write_clusters_file(self.mlst_download_dir)
  File "/usr/local/lib/python3.6/dist-packages/ariba-2.14.4-py3.6-linux-x86_64.egg/ariba/pubmlst_ref_preparer.py", line 49, in _load_fasta_files_and_write_clusters_file
    raise Error('Cannot find file "' + infile + '" for gene ' + gene_name)
ariba.pubmlst_ref_preparer.Error: Cannot find file "get_mlst/pubmlst_download/arcC.tfa" for gene arcC

**Comment by fino0000** [comment]
Hi. Did you solve this issue? I am having the same problem

**Comment by RotimiDada** [comment]
@fino0000, I got it fixed by installing the latest version of Ariba - 2.14.6 (I am not sure if there is a more recent version now.  I experienced the bug about 2 years ago). One of our IT guys suggested that I could get it fixed this way. By the way, are you using Ariba version 2.14.4? That's the version that produced the bug then. Cheers!
