### ISSUE TITLE
NCBI Database Download Error 

### ISSUE THREAD

**Issue by EmmaMills101** [sanger-pathogens/ariba#313]
Im trying to download the NCBI reference database and keep getting this error. I did force Biopython 1.76 to deal with the BioAlphabet issue, but that is the only modification I made. Thanks in advance

Processing record 392 of 5966 (accession NG_048387.1)
'AP018746.1'
gb_feature.qualifer not found
Traceback (most recent call last):
  File "/Users/emma/anaconda3/envs/ariba/bin/ariba", line 312, in <module>
    args.func(args)
  File "/Users/emma/anaconda3/envs/ariba/lib/python3.6/site-packages/ariba/tasks/getref.py", line 11, in run
    getter.run(options.outprefix)
  File "/Users/emma/anaconda3/envs/ariba/lib/python3.6/site-packages/ariba/ref_genes_getter.py", line 664, in run
    exec('self._get_from_' + self.ref_db + '(outprefix)')
  File "<string>", line 1, in <module>
  File "/Users/emma/anaconda3/envs/ariba/lib/python3.6/site-packages/ariba/ref_genes_getter.py", line 650, in _get_from_ncbi
    id=f"{id[0]}.{accession}",
TypeError: 'NoneType' object is not subscriptable

**Comment by learithe** [comment]
I am also getting this error.

**Comment by bajwamoneeb** [comment]
Me too..

**Comment by rpetit3** [comment]
Looking into that sequence, the issue is the GenBank file has "locus_tag" in the "note" field. I think this might be an issue to bring up with NCBI as well.

```
     CDS             101..820
                     /gene="repE"
                     /inference="COORDINATES: ab initio
                     prediction:Prodigal:2.6.3"
                     /inference="similar to AA sequence:UniProtKB:P62539"
     here------->    /note="locus_tag:MRY14229_p30010"
                     /codon_start=1
                     /transl_table=11
                     /product="replication initiation protein"
                     /protein_id="BBE81316.1"
                     /translation="MDKLLNKKIKVKQSNELTEAAYYLSLKAKRVLWLCLMQTYFTAS
                     VSEDDDEMAVLGDSTFKVKVADYEQIFQVSRNQAIKDVKEGVFELSRSAVIFYPKEGS
                     FDCVARPWLTEAGSRSARGIWEIEFNHKLLRYIYGLTNQFTTYSLRDCGSLRNPRTIR
                     LYESLAQFKSSGLWVTTHAWLNDRFLLPESQQKNLAELKRSFLDPALKQINEKTPLLA
                     KYSIDDSGKFLFSIIDKQNPV"
```

**Comment by cpeeters** [comment]
I have the same issue when trying to download latest version of ncbi reference db, but now on other accession=

```
Processing record 795 of 6243 (accession NG_048402.1)
'AP018746.1'
gb_feature.qualifer not found
Traceback (most recent call last):
  File "/usr/local/bin/ariba", line 312, in <module>
    args.func(args)
  File "/home/cpeeters/.local/lib/python3.7/site-packages/ariba/tasks/getref.py", line 11, in run
    getter.run(options.outprefix)
  File "/home/cpeeters/.local/lib/python3.7/site-packages/ariba/ref_genes_getter.py", line 664, in run
    exec('self._get_from_' + self.ref_db + '(outprefix)')
  File "<string>", line 1, in <module>
  File "/home/cpeeters/.local/lib/python3.7/site-packages/ariba/ref_genes_getter.py", line 650, in _get_from_ncbi
    id=f"{id[0]}.{accession}",
TypeError: 'NoneType' object is not subscriptable
```

Someone knows how to fix this (either in ariba, or in the source genbank entry)?

I tried ARIBA on a batch of genomes using CARD and really love the results, but I would need NCBI reference DB instead for this dataset, so any help is much appreciated!
