### ISSUE TITLE
NCBI Data Download Error

### ISSUE THREAD

**Issue by hackerzone85** [sanger-pathogens/ariba#316]
```javascript
E-fetching 6055 genbank records from BioProject PRJNA313047 and writing to.  This may take a while.
Parsing genbank records.
'NG_074760.1'
Processing record 1 of 6055 (accession NG_074760.1)
'NG_074759.1'
.....
Processing record 512 of 6055 (accession NG_048387.1)
'AP018746.1'
gb_feature.qualifer not found
Traceback (most recent call last):
  File "/home/hacker/anaconda3/envs/ariba/bin/ariba", line 312, in <module>
    args.func(args)
  File "/home/hacker/anaconda3/envs/ariba/lib/python3.6/site-packages/ariba/tasks/getref.py", line 11, in run
    getter.run(options.outprefix)
  File "/home/hacker/anaconda3/envs/ariba/lib/python3.6/site-packages/ariba/ref_genes_getter.py", line 664, in run
    exec('self._get_from_' + self.ref_db + '(outprefix)')
  File "<string>", line 1, in <module>
  File "/home/hacker/anaconda3/envs/ariba/lib/python3.6/site-packages/ariba/ref_genes_getter.py", line 650, in _get_from_ncbi
    id=f"{id[0]}.{accession}",
TypeError: 'NoneType' object is not subscriptable
'''

**Comment by rpetit3** [comment]
Hi @hackerzone85

This looks related to https://github.com/sanger-pathogens/ariba/issues/313#issuecomment-877481825
