### ISSUE TITLE
Failed cluster: cluster

### ISSUE THREAD

**Issue by Iqrarshad** [sanger-pathogens/ariba#330]
Hi, I am trying to run Ariba on my samples but it was giving an error. I installed dependencies with recommended versions. I installed bcftools 1.3.1. But still I am getting this error. Pleas guide me what to do.

ariba run out.more_virulence.prepareref 1_S1_L001_R1.fastq 1_S1_L001_R2.fastq 1_out.more_virulence.mygenome

cluster detected 1 threads available to it
mpileup: invalid option -- 't'
Failed cluster: cluster
Other clusters failed. Will not start cluster cluster_1
Other clusters failed. Will not start cluster cluster_2
Other clusters failed. Will not start cluster cluster_3
Other clusters failed. Will not start cluster cluster_4
Other clusters failed. Will not start cluster cluster_5
Other clusters failed. Will not start cluster cluster_6
Other clusters failed. Will not start cluster cluster_7
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ariba/clusters.py", line 612, in run
    self._run()
  File "/usr/local/lib/python3.10/dist-packages/ariba/clusters.py", line 646, in _run
    raise Error('At least one cluster failed! Stopping...')
ariba.clusters.Error: At least one cluster failed! Stopping...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ariba", line 312, in <module>
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/ariba/tasks/run.py", line 65, in run
    c.run()
  File "/usr/local/lib/python3.10/dist-packages/ariba/clusters.py", line 615, in run
    raise Error('Something went wrong during ariba run. Cannot continue. Error was:\n' + str(err))
ariba.clusters.Error: Something went wrong during ariba run. Cannot continue. Error was:
At least one cluster failed! Stopping...

**Comment by TNVN2022** [comment]
I have the same issue with your. Did you find the solution? Can you please share to me?
