### ISSUE TITLE
Test run seems to not work properly

### ISSUE THREAD

**Issue by marcellobeltrami** [sanger-pathogens/ariba#338]
Error when running test 

___________________________ Assembling each cluster ___________________________
Will run 1 cluster(s) in parallel
Not constructing cluster cluster because it only has 2 reads (1 of 9)
Constructing cluster cluster_1 (2 of 9)
Constructing cluster cluster_2 (3 of 9)
Constructing cluster cluster_3 (4 of 9)
Constructing cluster cluster_4 (5 of 9)
Constructing cluster gene (6 of 9)
Constructing cluster gene_1 (7 of 9)
Constructing cluster noncoding (8 of 9)
Constructing cluster noncoding_1 (9 of 9)
Start running cluster cluster_1 in directory /home/marcello/Test_data/ariba/test_2/OUT/ariba.tmp.9516apn8/cluster_1
cluster_1 detected 1 threads available to it
mpileup: invalid option -- 't'
Failed cluster: cluster_1
Finished running cluster cluster_1 in directory /home/marcello/Test_data/ariba/test_2/OUT/ariba.tmp.9516apn8/cluster_1
Deleting cluster dir /home/marcello/Test_data/ariba/test_2/OUT/ariba.tmp.9516apn8/cluster_1
Other clusters failed. Will not start cluster cluster_2
Other clusters failed. Will not start cluster cluster_3
Other clusters failed. Will not start cluster cluster_4
Other clusters failed. Will not start cluster gene
Other clusters failed. Will not start cluster gene_1
Other clusters failed. Will not start cluster noncoding
Other clusters failed. Will not start cluster noncoding_1
Final value of remaining_clusters counter: Value('l', 7)
Finished assembling clusters

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ariba/clusters.py", line 612, in run
    self._run()
  File "/usr/local/lib/python3.10/dist-packages/ariba/clusters.py", line 646, in _run
    raise Error('At least one cluster failed! Stopping...')
ariba.clusters.Error: At least one cluster failed! Stopping...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ariba", line 312, in <module>
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/ariba/tasks/run.py", line 65, in run
    c.run()
  File "/usr/local/lib/python3.10/dist-packages/ariba/clusters.py", line 615, in run
    raise Error('Something went wrong during ariba run. Cannot continue. Error was:\n' + str(err))
ariba.clusters.Error: Something went wrong during ariba run. Cannot continue. Error was:
At least one cluster failed! Stopping...

Something went wrong. See above for error message(s). Return code was 1

**Comment by VictorPizarroR** [comment]
Hello! @marcellobeltrami how have solved it? I've this same error now.

**Comment by marcellobeltrami** [comment]
Hello Victor. It has been a while, but I went back and managed to get it to work. Reading around it seems to be an issues with dependencies being out of date. Your best option is to use the docker image provided here:  

https://hub.docker.com/layers/sangerpathogens/ariba/release-v2.14.6/images/sha256-643c72186bb8fcadce1bc780e6f6a791dd124fe3c5622df383d3b51100e9bf46?context=explore 

For instructions on how to run the docker image look at the ariba repo as they provide a general good guide. 

I am happy to provide further help if you are not unfamiliar with docker.
